# Base image
FROM python:3.9-slim

# Set the working dir
WORKDIR /app

# Copy  the requirements.txt file into the container
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy the Flask app into the container 
COPY flask_app.py .

# Expose the port for the Flask app
EXPOSE 5000

# Start the Flask app
CMD [ "python", "flask-app.py" ]

