[api]
api_url="http://3.20.235.193/postdata"

[s3]
bucket='wcd-python-cloud-project'
folder='input'

[db]
host='ctkadxcqu2bl.us-east-2.rds.amazonaws.com'
port=3306
database='database'
schema='superstore'