version: '3.9'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db:27017
    env_file:
      - .env
    depends_on:
      - db
    container_name: "flask-app"

  db:
    image: "mongo:4.4"
    container_name: "mongodb"
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db"

volumes:
  mongo_data: